spring:
  profiles:
    active: test

---
spring:
  profiles: test
  application: springcloud-config-server-test

---
spring:
  profiles: release
  application: springcloud-config-server-release
---
spring:
  profiles: test
  application: provide-test
---
spring:
  profiles: release
  application: provide-release
