spring:
  profiles:
    active: test

---
spring:
  profiles: test
  application:
    name: springcloud-config-server-test
server:
  port: 8888

---
spring:
  profiles: release
  application:
    name: springcloud-config-server
server:
  port: 9999
