spring:
  profiles: test1
---
spring:
  profiles: test1
feign:
  hystrix:
    enabled: true
---
spring:
  profiles: test2
feign:
  hystrix:
    enabled: true
---
spring:
  profiles: release1
feign:
  hystrix:
    enabled: true
---
spring:
  profiles: release2
feign:
  hystrix:
    enabled: true

